
#[[plugins]]
#repo = 'lervag/vimtex'
#on_ft = ['tex']
#hook_add = '''
#let g:vimtex_compiler_progname = 'nvr'
#let g:vimtex_compiler_latexmk = { 'continuous' : 0 }
#let g:vimtex_quickfix_open_on_warning = 0
#'''
#hook_source = '''
#call deoplete#custom#var('omni', 'input_patterns', {
#      \ 'tex': g:vimtex#re#deoplete,
#      \ 'plaintex': g:vimtex#re#deoplete
#      \})
#'''
